- netflix-sel/README.md
Fixed the broken links on netflix-sel/README.md file
> Fixed the broken links on netflix-sel/README.md file

- README.md
Adding a link to the newest blog post with more details about Maestro into the ReadMe.
> adding newest blog link to the readme

- maestro-flow/src/main/java/com/netflix/maestro/flow/runtime/FlowOperation.java
----
----
Add an new interface for flow operations
> add an new interface for flow operations

- maestro-common/src/main/java/com/netflix/maestro/models/artifact/Artifact.java
- maestro-common/src/main/java/com/netflix/maestro/models/artifact/DynamicOutputArtifact.java
- maestro-common/src/test/java/com/netflix/maestro/models/artifact/DynamicOutputArtifactTest.java
- maestro-common/src/testFixtures/resources/fixtures/artifact/sample-artifacts.json
- maestro-common/src/testFixtures/resources/fixtures/artifact/sample-dynamic-output-artifact.json
- maestro-common/src/testFixtures/resources/fixtures/execution/sample-step-runtime-summary-with-dynamic-output.json
- maestro-common/src/testFixtures/resources/fixtures/execution/sample-step-runtime-summary.json
- maestro-common/src/testFixtures/resources/fixtures/typedsteps/sample-typed-step.json
- maestro-engine/src/main/java/com/netflix/maestro/engine/dao/OutputDataDao.java
- maestro-engine/src/main/java/com/netflix/maestro/engine/params/OutputDataManager.java
- maestro-engine/src/main/java/com/netflix/maestro/engine/params/ParamsManager.java
- maestro-engine/src/main/java/com/netflix/maestro/engine/tasks/MaestroTask.java
- maestro-engine/src/test/java/com/netflix/maestro/engine/dao/OutputDataDaoTest.java
- maestro-engine/src/test/java/com/netflix/maestro/engine/params/OutputDataManagerTest.java
- maestro-engine/src/test/java/com/netflix/maestro/engine/tasks/MaestroTaskTest.java
----
----
Add dynamic output feature to support step runtime to define outputs within the business logic.
> Add dynamic output feature to support step runtime to define outputs

- maestro-common/src/main/java/com/netflix/maestro/models/artifact/Artifact.java
- maestro-common/src/testFixtures/resources/fixtures/outputdata/sample-output-data.json
- maestro-engine/src/main/java/com/netflix/maestro/engine/dao/OutputDataDao.java
- maestro-engine/src/main/java/com/netflix/maestro/engine/dto/OutputData.java
- maestro-engine/src/main/java/com/netflix/maestro/engine/params/OutputDataManager.java
- maestro-engine/src/test/java/com/netflix/maestro/engine/params/OutputDataManagerTest.java
- maestro-kubernetes/src/main/java/com/netflix/maestro/engine/kubernetes/KubernetesRuntimeExecutor.java
- maestro-kubernetes/src/main/java/com/netflix/maestro/engine/stepruntime/KubernetesStepRuntime.java
- maestro-kubernetes/src/test/java/com/netflix/maestro/engine/stepruntime/KubernetesStepRuntimeTest.java
- maestro-server/src/main/java/com/netflix/maestro/server/config/MaestroWorkflowConfiguration.java
- maestro-server/src/main/java/com/netflix/maestro/server/runtime/Fabric8RuntimeExecutor.java
- maestro-server/src/main/resources/application-aws.yml
- maestro-server/src/main/resources/application.yml
- maestro-server/src/test/resources/samples/sample-kubernetes-output-wf.json
- maestro-signal/src/main/java/com/netflix/maestro/signal/dao/MaestroSignalBrokerDao.java
----
----
Support output data from a kubernetes job, including output params and dynamic output signals.
> Support output data from a kubernetes job

- maestro-flow/src/main/java/com/netflix/maestro/flow/actor/Actor.java
- maestro-flow/src/main/java/com/netflix/maestro/flow/actor/BaseActor.java
- maestro-flow/src/main/java/com/netflix/maestro/flow/actor/GroupActor.java
- maestro-flow/src/main/java/com/netflix/maestro/flow/dao/MaestroFlowDao.java
- maestro-flow/src/main/java/com/netflix/maestro/flow/engine/ExecutionContext.java
- maestro-flow/src/main/java/com/netflix/maestro/flow/engine/FlowExecutor.java
- maestro-flow/src/main/java/com/netflix/maestro/flow/models/FlowGroup.java
- maestro-flow/src/main/java/com/netflix/maestro/flow/properties/FlowEngineProperties.java
- maestro-flow/src/test/java/com/netflix/maestro/flow/actor/ActorBaseTest.java
- maestro-flow/src/test/java/com/netflix/maestro/flow/actor/ActorTest.java
- maestro-flow/src/test/java/com/netflix/maestro/flow/actor/BaseActorTest.java
- maestro-flow/src/test/java/com/netflix/maestro/flow/actor/GroupActorTest.java
- maestro-flow/src/test/java/com/netflix/maestro/flow/dao/MaestroFlowDaoTest.java
- maestro-flow/src/test/java/com/netflix/maestro/flow/engine/ExecutionContextTest.java
- maestro-flow/src/test/java/com/netflix/maestro/flow/engine/FlowExecutorTest.java
- maestro-server/src/main/java/com/netflix/maestro/server/runtime/RestBasedFlowOperation.java
----
----
Improve flow engine to check the liveness of the group actors.
Also support to post directly (no delay) the same type message.
> Improve flow engine to check the liveness of the group actors

- maestro-common/src/main/java/com/netflix/maestro/utils/IdHelper.java
- maestro-common/src/test/java/com/netflix/maestro/utils/IdHelperTest.java
- maestro-common/src/testFixtures/resources/fixtures/jobevents/sample-instance-flow-action-job-event.json
- maestro-engine/src/main/java/com/netflix/maestro/engine/dao/MaestroStepInstanceActionDao.java
- maestro-engine/src/main/java/com/netflix/maestro/engine/dao/MaestroWorkflowInstanceDao.java
- maestro-engine/src/main/java/com/netflix/maestro/engine/db/ForeachIterationOverview.java
- maestro-engine/src/main/java/com/netflix/maestro/engine/handlers/MaestroExecutionPreparer.java
- maestro-engine/src/main/java/com/netflix/maestro/engine/handlers/WorkflowRunner.java
- maestro-engine/src/main/java/com/netflix/maestro/engine/processors/InstanceActionJobEventProcessor.java
- maestro-engine/src/main/java/com/netflix/maestro/engine/processors/UpdateJobEventProcessor.java
- maestro-engine/src/main/java/com/netflix/maestro/engine/steps/ForeachStepRuntime.java
- maestro-engine/src/main/java/com/netflix/maestro/engine/steps/SubworkflowStepRuntime.java
- maestro-engine/src/test/java/com/netflix/maestro/engine/dao/MaestroWorkflowInstanceDaoTest.java
- maestro-engine/src/test/java/com/netflix/maestro/engine/handlers/MaestroExecutionPreparerTest.java
- maestro-engine/src/test/java/com/netflix/maestro/engine/handlers/WorkflowRunnerTest.java
- maestro-engine/src/test/java/com/netflix/maestro/engine/processors/InstanceActionJobEventProcessorTest.java
- maestro-flow/src/main/java/com/netflix/maestro/flow/actor/FlowActor.java
- maestro-flow/src/main/java/com/netflix/maestro/flow/actor/GroupActor.java
- maestro-queue/src/main/java/com/netflix/maestro/queue/jobevents/InstanceActionJobEvent.java
- maestro-queue/src/main/java/com/netflix/maestro/queue/models/MessageDto.java
----
----
Fix the way to generate flow references, which should include the run id
> Fix the way to generate flow references, which should include the run id

- maestro-server/src/main/java/com/netflix/maestro/server/handlers/MaestroRestExceptionHandler.java
----
----
fix the exception handler to include all the errors
> fix the exception handler to include all the errors

- maestro-aws/README.md
----
----
Update README.md to fix the bash command
> Update README.md to fix the bash command

- maestro-common/src/test/java/com/netflix/maestro/validations/BaseConstraintTest.java
- maestro-server/src/main/java/com/netflix/maestro/server/config/MaestroWorkflowConfiguration.java
----
----
Small improvement to make sure to use ApacheValidationProvider
> make sure to use ApacheValidationProvider

- README.md
----
----
Add community slack workspace info
> add community slack workspace info

- maestro-common/src/main/java/com/netflix/maestro/models/api/StepOutputDataRequest.java
- maestro-common/src/test/java/com/netflix/maestro/models/api/StepOutputDataRequestTest.java
- maestro-common/src/testFixtures/resources/fixtures/api/sample-output-data-request.json
- maestro-engine/src/test/java/com/netflix/maestro/engine/dao/MaestroDaoBaseTest.java
- maestro-engine/src/test/java/com/netflix/maestro/engine/dao/MaestroRunStrategyDaoTest.java
- maestro-engine/src/test/java/com/netflix/maestro/engine/dao/MaestroStepBreakpointDaoTest.java
- maestro-engine/src/test/java/com/netflix/maestro/engine/dao/MaestroStepInstanceActionDaoTest.java
- maestro-engine/src/test/java/com/netflix/maestro/engine/dao/MaestroStepInstanceDaoTest.java
- maestro-engine/src/test/java/com/netflix/maestro/engine/dao/MaestroWorkflowDaoTest.java
- maestro-engine/src/test/java/com/netflix/maestro/engine/dao/MaestroWorkflowDeletionDaoTest.java
- maestro-engine/src/test/java/com/netflix/maestro/engine/dao/MaestroWorkflowInstanceDaoTest.java
- maestro-engine/src/test/java/com/netflix/maestro/engine/dao/OutputDataDaoTest.java
- maestro-server/src/main/java/com/netflix/maestro/server/controllers/OutputDataController.java
- maestro-signal/src/test/java/com/netflix/maestro/signal/dao/MaestroBaseSignalDaoTest.java
----
----
Add output data APIs.
> Add output data APIs.

- maestro-server/src/main/java/com/netflix/maestro/server/controllers/StepBreakpointController.java
----
----
Add step breakpoint APIs
> add step breakpoint APIs

- maestro-aws/src/test/java/com/netflix/maestro/engine/publisher/SnsEventNotificationPublisherTest.java
- maestro-common/src/main/java/com/netflix/maestro/models/trigger/CronTimeTrigger.java
- maestro-common/src/main/java/com/netflix/maestro/models/trigger/IntervalTimeTrigger.java
- maestro-common/src/main/java/com/netflix/maestro/models/trigger/PredefinedTimeTrigger.java
- maestro-common/src/test/java/com/netflix/maestro/models/parameter/MapParameterTest.java
- maestro-engine/src/test/java/com/netflix/maestro/engine/params/OutputDataManagerTest.java
- maestro-engine/src/test/java/com/netflix/maestro/engine/processors/InstanceActionJobEventProcessorTest.java
- maestro-engine/src/test/java/com/netflix/maestro/engine/processors/StartWorkflowJobEventProcessorTest.java
- maestro-flow/src/main/java/com/netflix/maestro/flow/dao/MaestroFlowDao.java
- maestro-queue/src/test/java/com/netflix/maestro/queue/worker/MaestroQueueWorkerTest.java
- maestro-signal/src/test/java/com/netflix/maestro/signal/utils/SignalTriggerSubscriptionClientTest.java
- maestro-timetrigger/src/test/java/com/netflix/maestro/timetrigger/utils/MaestroWorkflowLauncherTest.java
----
----
fix some warnings from the build
> fix some warnings from the build

- maestro-common/src/main/java/com/netflix/maestro/models/Constants.java
- maestro-engine/src/main/java/com/netflix/maestro/engine/eval/MaestroParamExtension.java
- maestro-engine/src/main/java/com/netflix/maestro/engine/eval/StepInstanceAttributes.java
- maestro-engine/src/test/java/com/netflix/maestro/engine/eval/MaestroParamExtensionTest.java
- maestro-server/src/test/resources/samples/sample-kubernetes-env-wf.json
- maestro-server/src/test/resources/samples/sample-kubernetes-output-wf.json
----
----
Add a SEL function to get the value of error retries. Also add one example of k8s step to set env.
> Add a SEL function to get the value of error retries

- maestro-database/src/main/java/com/netflix/maestro/database/AbstractDatabaseDao.java
- maestro-engine/src/main/java/com/netflix/maestro/engine/steps/ForeachStepRuntime.java
- maestro-engine/src/main/java/com/netflix/maestro/engine/steps/SubworkflowStepRuntime.java
- maestro-engine/src/main/java/com/netflix/maestro/engine/tasks/MaestroTask.java
----
----
Improve Maestro to retry certain db errors, e.g. connection is closed.
> Improve Maestro to retry certain db errors, e.g. connection is closed.

- maestro-flow/src/main/java/com/netflix/maestro/flow/actor/BaseActor.java
- maestro-flow/src/main/java/com/netflix/maestro/flow/engine/ExecutionContext.java
- maestro-flow/src/test/java/com/netflix/maestro/flow/actor/BaseActorTest.java
- maestro-flow/src/test/java/com/netflix/maestro/flow/engine/ExecutionContextTest.java
----
----
deduplicate actions to avoid unnecessary executions in the flow engine
> deduplicate actions to avoid unnecessary executions in the flow engine

- maestro-engine/src/main/java/com/netflix/maestro/engine/metrics/MetricConstants.java
- maestro-engine/src/main/java/com/netflix/maestro/engine/tasks/MaestroGateTask.java
- maestro-engine/src/main/java/com/netflix/maestro/engine/tasks/MaestroStartTask.java
- maestro-engine/src/main/java/com/netflix/maestro/engine/tasks/MaestroTagPermitTask.java
- maestro-engine/src/main/java/com/netflix/maestro/engine/tasks/MaestroTask.java
- maestro-engine/src/test/java/com/netflix/maestro/engine/dao/MaestroTagPermitDaoTest.java
- maestro-flow/src/test/java/com/netflix/maestro/flow/actor/BaseActorTest.java
- maestro-server/src/main/resources/application-aws.yml
- maestro-server/src/main/resources/application.yml
----
----
add extra metrics and small improvements related to tag permit feature
> add extra metrics and small improvements related to tag permit feature

- maestro-common/src/main/java/com/netflix/maestro/models/timeline/TimelineActionEvent.java
- maestro-engine/src/main/java/com/netflix/maestro/engine/concurrency/MaestroTagPermitManager.java
- maestro-engine/src/main/java/com/netflix/maestro/engine/concurrency/TagPermitManager.java
- maestro-engine/src/main/java/com/netflix/maestro/engine/tasks/MaestroTagPermitTask.java
- maestro-engine/src/main/java/com/netflix/maestro/engine/tasks/MaestroTask.java
----
----
Slightly improve the code readability with additional comments.
> Slightly improve the code readability with additional comments.

- maestro-common/src/main/java/com/netflix/maestro/exceptions/MaestroRuntimeException.java
----
----
Fix the http status code in MaestroRuntimeException.
> Fix the http status code in MaestroRuntimeException.

- maestro-engine/src/main/java/com/netflix/maestro/engine/handlers/MaestroExecutionPreparer.java
- maestro-engine/src/test/java/com/netflix/maestro/engine/dao/MaestroStepInstanceActionDaoTest.java
- maestro-flow/src/main/java/com/netflix/maestro/flow/Constants.java
- maestro-flow/src/main/java/com/netflix/maestro/flow/actor/FlowActor.java
----
----
Improve the code and a unit test
> Improve the code and a unit test
